import Header from '@/components/Header/Header';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};
import './global.css';

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <main className="bg-gradient-to-b from-blue-50 to-white">
          <Header />
          <main className={'h-[calc(100vh-64px)] mt-16'}>{children}</main>
        </main>
      </body>
    </html>
  );
}
